export default {
  SET_ALL_MOVIES: 'SET_ALL_MOVIES',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_LOADER_VALUE: 'TOGGLE_LOADER',
  REMOVE_MOVIE: 'REMOVE_MOVIE',
  SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
  SHOW_TOAST_NOTIFY: 'SHOW_TOAST_NOTIFY',
  TOGGLE_FAVOURITES: 'ADD_TO_FAVOURITES',
  SET_FAVOURITE_MOVIE: 'SET_FAVOURITE_MOVIE',
  REMOVE_FAVOURITE_MOVIE: 'REMOVE_FAVOURITE_MOVIE',
  SET_APP_START: 'SET_APP_START',
  SET_POSTER: 'SET_POSTER',
};
